
nginx:
    image: nginx:latest
    ports:
        - 80:80
    links:
        - php
    volumes_from:
        - app
    volumes:
        - ./docker/nginx/:/etc/nginx/conf.d/

php:
    image: kahunacoder/docker-laravel-php
    expose:
        - 9000
    links:
        - mysql
    volumes_from:
        - app

app:
    image: kahunacoder/docker-laravel-app
    volumes:
        - ./app/:/app
        - /storage
    working_dir: /app
    command: "true"

mysql:
    image: mysql:5.6
    volumes_from:
        - data
    ports:
        - 3306:3306
    env_file: ./app/.env

data:
    image: mysql:5.6
    volumes:
        - /var/lib/mysql
    command: "true"

composer:  
    image: composer/composer:master
    volumes_from:
        - app
    working_dir: /app

redis:
    image: redis

node:
    image: node:onbuild
    volumes_from:
        - app
    ports: 
        - 8125:8125
    links:
        - redis
        - php
    working_dir: /app
    entrypoint: ['npm', 'start']

## Developer Tools
npm:
    image: node:onbuild
    volumes_from:
        - app
    links:
        - php
    working_dir: /app
    entrypoint: ['npm']

artisan:  
      image: kahunacoder/docker-laravel-artisian
      volumes_from:
        - app
      links:
        - mysql

gulp:
    image: kahunacoder/docker-laravel-gulp
    volumes_from:
        - app
    ports:
        - "3000:3000"
        - "3001:3001"
    working_dir: /app
    entrypoint: ['gulp']
